DOXYFILE = 'Doxyfile'

LINKS_NAVBAR1 = [
    (None, 'pages', [
        (None, 'about'),
#        (None, 'examples'),
    ])
]
LINKS_NAVBAR2 = [
    (None, 'namespaces', []),
    (None, 'annotated', []),
    (None, 'files', []),
]

FINE_PRINT = """<p>Spline docs. Part of the <a
href="https://magnum.graphics/">Spline project</a>, copyright © <a
href="http://dlpeterson.com/">Dale L. Peterson</a> and <a href="credits-contributors.html">contributors</a>, 2020&ndash;2021.<br />Generated by <a href="https://doxygen.org/">Doxygen</a> {doxygen_version} and <a href="https://mcss.mosra.cz/">m.css</a>.</p>"""
