name: MacOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.10.2

      - name: configure
        run: cmake -G Ninja -S test -B build -DCMAKE_BUILD_TYPE=Release

      - name: build
        run: cmake --build build -v

      - name: test
        run: ctest --test-dir build --output-on-failure
